version: "2"
services:
  prometheus:
    image: "prom/prometheus"
    network_mode: "host"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./first.rules:/etc/prometheus/first.rules
      - ./prometheus:/prometheus

#  alertmanager:
#    image: "quay.io/prometheus/alertmanager"
#    network_mode: "host"
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  node_exporter:
    image: "prom/node-exporter"
    network_mode: "host"

  grafana:
    image: "grafana/grafana"
    network_mode: "host"

  scollector:
    image: "diyan/scollector"
    entrypoint : "/usr/local/bin/scollector -h=127.0.0.1:9107"
    network_mode: "host"
  
  scollector-exporter:
    image: "diyan/prom-scollector-exporter"
    entrypoint: "/usr/local/bin/prometheus_scollector -http=0.0.0.0:9107"
    network_mode: "host"


